# Generated by Django 3.2.7 on 2021-10-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_addresses_city_country_customerprofile_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(default='0', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
    ]
