# Generated by Django 3.2.7 on 2021-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20211009_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='area',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='flat',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='landmark',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
