# Generated by Django 3.2.7 on 2021-10-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_auto_20211010_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
    ]
