# Generated by Django 3.2.7 on 2021-10-07 10:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('RAM', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'The RAM should be within bellow Example')])),
                ('ROM', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'The ROM should be within bellow Example')])),
                ('processor', models.CharField(max_length=50)),
                ('warranty', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Warranty should be Greater than Zero')])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'The Prize should be Greater than Zero')])),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Stock should be Greater than Zero')])),
                ('image', models.FileField(blank=True, default='Mobile.jpg', upload_to='Mobile/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('RAM', models.IntegerField()),
                ('ROM', models.IntegerField()),
                ('processor', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=64)),
                ('warranty', models.IntegerField(null=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.FileField(blank=True, default='Laptop.jpg', upload_to='images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'The Quantity should be Greater than Zero')])),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1, 'The Prize should be Greater than Zero')])),
                ('warranty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Warranty should be Greater than Zero')])),
                ('image', models.FileField(blank=True, default='Grocery.jpg', upload_to='Grocery/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('Size', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('Price', models.FloatField(max_length=64)),
                ('stock', models.IntegerField(null=True)),
                ('image', models.FileField(blank=True, default='Grocery.jpg', upload_to='Footwear/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('Price', models.FloatField(max_length=64)),
                ('stock', models.IntegerField(null=True)),
                ('image', models.FileField(blank=True, default='Grocery.jpg', upload_to='Cosmetics/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('Size', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
                ('Price', models.FloatField(max_length=64)),
                ('stock', models.IntegerField(null=True)),
                ('image', models.FileField(blank=True, default='Grocery.jpg', upload_to='Clothing/images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.seller')),
            ],
        ),
    ]
