# Generated by Django 3.2.7 on 2021-10-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='warranty',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
