# Generated by Django 3.2.7 on 2021-10-07 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_alter_laptop_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='warranty',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1, 'Warranty should be Greater than Zero')]),
            preserve_default=False,
        ),
    ]
